### ISSUE TITLE
Mouse not working

### ISSUE THREAD

**Issue by dubl3a** [Triang3l/WebQuake#27]
Tested on latest versions of Chome and Firefox.  Mouse is not captured by the web browser

**Comment by quantuumsnot** [comment]
It was fixed with Pull Request #23

**Comment by P373R** [comment]
Not for that but after Firefox 49, the mouse is Still not working/locks on screen... i am using currently firefox 56, but nothing. Still Wont lock the mouse, therefor, the mouselook is unusable... so it is not fixed.

**Comment by LiamKarlMitchell** [comment]
Is working for me in chrome and firefox today.
